apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  containers:
    - name: hello-app
      image: wschaefer42/kube-hello-app:v1
      imagePullPolicy: Always
  restartPolicy: Always
